name: stimulus_gen_3_7
channels:
  - defaults
dependencies:
  - attrs=19.3.0
  - blas=1.0
  - ca-certificates=2019.10.16
  - certifi=2019.9.11
  - cloudpickle=1.2.2
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.6.0
  - decorator=4.4.1
  - freetype=2.9.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.6.1
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libtiff=4.0.10
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - more-itertools=7.2.0
  - networkx=2.4
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=19.2
  - pcre=8.43
  - pillow=6.2.1
  - pip=19.3.1
  - pluggy=0.13.1
  - py=1.8.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pytest=5.3.0
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.9.7
  - scikit-image=0.15.0
  - scipy=1.3.1
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zc.lockfile=2.0
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - arabic-reshaper==2.0.15
    - astunparse==1.6.2
    - cffi==1.13.2
    - chardet==3.0.4
    - cryptography==2.8
    - esprima==4.0.1
    - et-xmlfile==1.0.1
    - freetype-py==2.1.0.post1
    - future==0.18.2
    - future-fstrings==1.2.0
    - gevent==1.4.0
    - gitdb2==2.0.6
    - gitpython==3.0.5
    - glfw==1.8.4
    - greenlet==0.4.15
    - idna==2.8
    - imageio-ffmpeg==0.3.0
    - jdcal==1.4.1
    - json-tricks==3.13.4
    - moviepy==1.0.1
    - msgpack==0.6.2
    - msgpack-numpy==0.4.4.3
    - numexpr==2.7.0
    - openpyxl==3.0.2
    - pandas==0.25.3
    - proglog==0.1.9
    - progressbar==2.5
    - psutil==5.6.7
    - psychopy==3.2.3
    - pycparser==2.19
    - pygame==1.9.6
    - pyglet==1.4.8
    - pyopengl==3.1.0
    - pyopenssl==19.1.0
    - pyosf==1.0.5
    - pyparallel==0.2.2
    - pyserial==3.4
    - python-bidi==0.4.2
    - python-gitlab==1.13.0
    - pyyaml==5.1.2
    - pyzmq==18.1.1
    - questplus==0.0.5
    - requests==2.22.0
    - smmap2==2.0.5
    - sounddevice==0.3.14
    - soundfile==0.10.3.post1
    - tables==3.6.1
    - tifffile==2019.7.26
    - tqdm==4.39.0
    - urllib3==1.25.7
    - xarray==0.14.1
    - xlrd==1.2.0

